apiVersion: apps/v1
kind: Deployment

metadata:
  name: pcode-lofi-deployment
  namespace: pcode
  labels:
    app: pcode-lofi

spec:
  selector:
    matchLabels:
      app: pcode-lofi
  replicas: 1
  template:
    metadata:
      labels:
        app: pcode-lofi
    spec:
      containers:
      - name: pcode-lofi-image
        image: ghcr.io/momozahara/pcode-lofi:1.0.1
        imagePullPolicy: Always
        ports:
          -  containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database
              key: DATABASE_URL_LOFI
