apiVersion: v1
kind: Service

metadata:
  name: pcode-lofi-service
  namespace: pcode
  labels:
    app: pcode-lofi

spec:
  selector:
    app: pcode-lofi
  type: NodePort
  clusterIP: 10.152.183.20
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30020
